# Done to increase the memory available to the Gradle daemon.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.5+26.3
modmenu_version=20.0.0-alpha.1
cloth_config_version=26.1.154

# Mod Properties
mod_version=1.0.6
maven_group=net.netheritearmourplus
archives_base_name=netheritearmourplus
